### ISSUE TITLE
Suggestion: Consider alternate method name for Key generation

### ISSUE THREAD

**Issue by tep** [IngCr3at1on/smokering#4]
Per your RFC in #reviews -- regarding: https://github.com/IngCr3at1on/smokering/blob/c9e16dd3e7dccfc4bb9b47143885eb97c0b48c43/smokering.go#L29

A common pattern I like to use, when I have a package level constructor named `New` returning a factory object that itself creates some other object, is to use the child object's name as the name of the factory method that creates it.

In this case, instead of:
```go
    func (kr *Smokering) New(...
```

... you'd have:
```go
    func (kr *Smokering) Key(...
```

I've found that it can make things a lot clearer 6 months down the road (given that the word `New` is often grossly overloaded).

**Comment by IngCr3at1on** [comment]
This is implemented in cfba85f1d06d6a3d4573efa5aaa3495d9e91125f thanks @tep for the suggestion.
